/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlanId = IDL.Variant({
  'biannual' : IDL.Null,
  'annual' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const StaffInput = IDL.Record({
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'monthlySalary' : IDL.Nat,
});
export const StaffId = IDL.Nat;
export const StudentId = IDL.Nat;
export const ComplaintInput = IDL.Record({
  'studentId' : IDL.Opt(StudentId),
  'description' : IDL.Text,
  'roomNumber' : IDL.Text,
});
export const ComplaintId = IDL.Nat;
export const NoteId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'emptyRoom' : IDL.Null,
  'complaintUpdate' : IDL.Null,
  'paymentOverdue' : IDL.Null,
  'rentDue' : IDL.Null,
});
export const NotificationInput = IDL.Record({
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'message' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Nat),
});
export const NotificationId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'partial' : IDL.Null,
});
export const PaymentInput = IDL.Record({
  'status' : PaymentStatus,
  'month' : IDL.Nat,
  'studentId' : StudentId,
  'note' : IDL.Opt(IDL.Text),
  'year' : IDL.Nat,
  'rentDue' : IDL.Nat,
  'paidAmount' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const ReminderId = IDL.Nat;
export const RoomInput = IDL.Record({
  'seatCount' : IDL.Nat,
  'roomNumber' : IDL.Text,
});
export const RoomId = IDL.Nat;
export const SeatType = IDL.Variant({ 'typeA' : IDL.Null, 'typeB' : IDL.Null });
export const StudentInput = IDL.Record({
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'idProofText' : IDL.Text,
  'phone' : IDL.Text,
  'roomId' : IDL.Opt(RoomId),
  'seatType' : IDL.Opt(SeatType),
});
export const UdharCategory = IDL.Variant({
  'other' : IDL.Null,
  'milk' : IDL.Null,
  'grocery' : IDL.Null,
});
export const UdharInput = IDL.Record({
  'studentId' : StudentId,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : UdharCategory,
  'amount' : IDL.Nat,
});
export const UdharId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const StaffAttendance = IDL.Record({
  'status' : AttendanceStatus,
  'staffId' : StaffId,
  'date' : IDL.Text,
});
export const BuildingStats = IDL.Record({
  'totalEmptyRooms' : IDL.Nat,
  'totalSeats' : IDL.Nat,
  'totalActiveStudents' : IDL.Nat,
});
export const ComplaintStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Complaint = IDL.Record({
  'id' : ComplaintId,
  'status' : ComplaintStatus,
  'studentId' : IDL.Opt(StudentId),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'roomNumber' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const HostelSettings = IDL.Record({ 'lateFeePerMonth' : IDL.Nat });
export const Amount = IDL.Nat;
export const SeatSummary = IDL.Record({
  'month' : IDL.Nat,
  'pricePerSeatA' : Amount,
  'pricePerSeatB' : Amount,
  'year' : IDL.Nat,
  'revenueA' : Amount,
  'revenueB' : Amount,
  'totalBookedSeats' : IDL.Nat,
  'totalRevenue' : Amount,
  'totalCapacity' : IDL.Nat,
  'emptySeats' : IDL.Nat,
  'bookedSeatsA' : IDL.Nat,
  'bookedSeatsB' : IDL.Nat,
});
export const MonthKey = IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat });
export const MonthlyExpenses = IDL.Record({
  'key' : MonthKey,
  'other' : Amount,
  'rent' : Amount,
  'electricity' : Amount,
  'staffSalary' : Amount,
});
export const MonthlyProfit = IDL.Record({
  'month' : IDL.Nat,
  'revenue' : Amount,
  'year' : IDL.Nat,
  'totalExpenses' : Amount,
  'profit' : IDL.Int,
});
export const MonthlyStaffExpense = IDL.Record({
  'month' : IDL.Nat,
  'presentDays' : IDL.Nat,
  'year' : IDL.Nat,
  'workingDays' : IDL.Nat,
  'totalSalary' : IDL.Nat,
});
export const SubscriptionStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'expired' : IDL.Null,
});
export const SubscriptionRecord = IDL.Record({
  'status' : SubscriptionStatus,
  'planId' : IDL.Opt(PlanId),
  'expiryDate' : IDL.Opt(IDL.Int),
  'userId' : IDL.Principal,
  'trialStartDate' : IDL.Int,
});
export const SubscriptionStatusResult = IDL.Record({
  'status' : SubscriptionStatus,
  'daysRemaining' : IDL.Nat,
});
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Nat),
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'month' : IDL.Nat,
  'studentId' : StudentId,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'dueDate' : IDL.Int,
  'lateFee' : IDL.Nat,
  'paidDate' : IDL.Opt(IDL.Int),
  'rentDue' : IDL.Nat,
  'paidAmount' : IDL.Nat,
});
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'title' : IDL.Text,
  'remindAt' : IDL.Int,
  'createdAt' : IDL.Int,
  'isDone' : IDL.Bool,
  'message' : IDL.Text,
});
export const Room = IDL.Record({
  'id' : RoomId,
  'createdAt' : IDL.Int,
  'seatCount' : IDL.Nat,
  'roomNumber' : IDL.Text,
  'occupiedSeats' : IDL.Nat,
});
export const RoomSummary = IDL.Record({
  'id' : RoomId,
  'status' : IDL.Variant({
    'full' : IDL.Null,
    'empty' : IDL.Null,
    'partial' : IDL.Null,
  }),
  'seatCount' : IDL.Nat,
  'roomNumber' : IDL.Text,
  'occupiedSeats' : IDL.Nat,
});
export const SeatConfig = IDL.Record({
  'pricePerSeatA' : Amount,
  'pricePerSeatB' : Amount,
  'totalCapacity' : IDL.Nat,
});
export const Staff = IDL.Record({
  'id' : StaffId,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'monthlySalary' : IDL.Nat,
});
export const StaffSalaryEntry = IDL.Record({
  'earnedSalary' : IDL.Nat,
  'staffId' : StaffId,
  'presentDays' : IDL.Nat,
  'name' : IDL.Text,
  'monthlySalary' : IDL.Nat,
  'totalWorkingDays' : IDL.Nat,
});
export const StaffSalaryReport = IDL.Record({
  'month' : IDL.Nat,
  'totalEarned' : IDL.Nat,
  'year' : IDL.Nat,
  'entries' : IDL.Vec(StaffSalaryEntry),
  'workingDays' : IDL.Nat,
});
export const StudentStatus = IDL.Variant({
  'active' : IDL.Null,
  'vacated' : IDL.Null,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'status' : StudentStatus,
  'documentKey' : IDL.Opt(IDL.Text),
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'photoKey' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'idProofText' : IDL.Text,
  'phone' : IDL.Text,
  'roomId' : IDL.Opt(RoomId),
  'leaveDate' : IDL.Opt(IDL.Int),
  'seatType' : IDL.Opt(SeatType),
});
export const UdharEntry = IDL.Record({
  'id' : UdharId,
  'studentId' : StudentId,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isPaid' : IDL.Bool,
  'category' : UdharCategory,
  'amount' : IDL.Nat,
});
export const UdharSummary = IDL.Record({
  'studentId' : StudentId,
  'totalOutstanding' : IDL.Nat,
  'entries' : IDL.Vec(UdharEntry),
});
export const StudentSummary = IDL.Record({
  'id' : StudentId,
  'status' : StudentStatus,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'roomNumber' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'roomId' : IDL.Opt(RoomId),
  'leaveDate' : IDL.Opt(IDL.Int),
});
export const YearlyChartEntry = IDL.Record({
  'month' : IDL.Nat,
  'profit' : IDL.Int,
});
export const ExpenseInput = IDL.Record({
  'other' : Amount,
  'rent' : Amount,
  'electricity' : Amount,
  'staffSalary' : Amount,
});

export const idlService = IDL.Service({
  'activateSubscription' : IDL.Func([PlanId], [], []),
  'addStaff' : IDL.Func(
      [StaffInput],
      [IDL.Variant({ 'ok' : StaffId, 'err' : IDL.Text })],
      [],
    ),
  'cancelSubscription' : IDL.Func([], [], []),
  'clearAllNotifications' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createComplaint' : IDL.Func(
      [ComplaintInput],
      [IDL.Variant({ 'ok' : ComplaintId, 'err' : IDL.Text })],
      [],
    ),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
  'createNotification' : IDL.Func(
      [NotificationInput],
      [IDL.Variant({ 'ok' : NotificationId, 'err' : IDL.Text })],
      [],
    ),
  'createPayment' : IDL.Func(
      [PaymentInput],
      [IDL.Variant({ 'ok' : PaymentId, 'err' : IDL.Text })],
      [],
    ),
  'createReminder' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [ReminderId], []),
  'createRoom' : IDL.Func(
      [RoomInput],
      [IDL.Variant({ 'ok' : RoomId, 'err' : IDL.Text })],
      [],
    ),
  'createStudent' : IDL.Func(
      [StudentInput],
      [IDL.Variant({ 'ok' : StudentId, 'err' : IDL.Text })],
      [],
    ),
  'createUdharEntry' : IDL.Func(
      [UdharInput],
      [IDL.Variant({ 'ok' : UdharId, 'err' : IDL.Text })],
      [],
    ),
  'deleteComplaint' : IDL.Func(
      [ComplaintId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'deletePayment' : IDL.Func(
      [PaymentId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
  'deleteRoom' : IDL.Func(
      [RoomId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteStudent' : IDL.Func(
      [StudentId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUdharEntry' : IDL.Func(
      [UdharId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAttendanceByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(StaffAttendance)],
      ['query'],
    ),
  'getBuildingStats' : IDL.Func([], [BuildingStats], ['query']),
  'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getHostelSettings' : IDL.Func([], [HostelSettings], ['query']),
  'getMonthSeatSummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(SeatSummary)],
      ['query'],
    ),
  'getMonthlyExpenses' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(MonthlyExpenses)],
      ['query'],
    ),
  'getMonthlyProfit' : IDL.Func([IDL.Nat, IDL.Nat], [MonthlyProfit], ['query']),
  'getMonthlyStaffExpense' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlyStaffExpense],
      ['query'],
    ),
  'getMySubscription' : IDL.Func([], [IDL.Opt(SubscriptionRecord)], ['query']),
  'getMySubscriptionStatus' : IDL.Func([], [SubscriptionStatusResult], []),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getRoom' : IDL.Func([RoomId], [IDL.Opt(Room)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
  'getSeatConfig' : IDL.Func([], [IDL.Opt(SeatConfig)], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getStaffAttendance' : IDL.Func(
      [StaffId, IDL.Nat, IDL.Nat],
      [IDL.Vec(StaffAttendance)],
      ['query'],
    ),
  'getStaffSalaryReport' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [StaffSalaryReport],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentPayments' : IDL.Func([StudentId], [IDL.Vec(Payment)], ['query']),
  'getStudentUdhar' : IDL.Func([StudentId], [UdharSummary], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(StudentSummary)], ['query']),
  'getTotalExpenses' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getUdharEntries' : IDL.Func([], [IDL.Vec(UdharEntry)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getYearlyProfitChart' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(YearlyChartEntry)],
      ['query'],
    ),
  'markAllNotificationsRead' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markAttendance' : IDL.Func(
      [StaffId, IDL.Text, AttendanceStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markNotificationRead' : IDL.Func(
      [NotificationId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markReminderDone' : IDL.Func([ReminderId], [IDL.Bool], []),
  'markUdharPaid' : IDL.Func(
      [UdharId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeStaff' : IDL.Func(
      [StaffId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setMonthlyBooking' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'setMonthlyExpenses' : IDL.Func([IDL.Nat, IDL.Nat, ExpenseInput], [], []),
  'setSeatConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'startTrial' : IDL.Func([], [], []),
  'stripeWebhook' : IDL.Func([IDL.Principal, PlanId], [], []),
  'updateComplaintStatus' : IDL.Func(
      [ComplaintId, ComplaintStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateHostelSettings' : IDL.Func(
      [HostelSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updatePayment' : IDL.Func(
      [PaymentId, PaymentInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateReminder' : IDL.Func(
      [ReminderId, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Bool],
      [],
    ),
  'updateRoom' : IDL.Func(
      [RoomId, RoomInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateStaff' : IDL.Func(
      [StaffId, StaffInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateStudent' : IDL.Func(
      [StudentId, StudentInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateStudentDocument' : IDL.Func(
      [StudentId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateStudentPhoto' : IDL.Func(
      [StudentId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateUdharEntry' : IDL.Func(
      [UdharId, UdharInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'vacateStudent' : IDL.Func(
      [StudentId, IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlanId = IDL.Variant({
    'biannual' : IDL.Null,
    'annual' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const StaffInput = IDL.Record({
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'monthlySalary' : IDL.Nat,
  });
  const StaffId = IDL.Nat;
  const StudentId = IDL.Nat;
  const ComplaintInput = IDL.Record({
    'studentId' : IDL.Opt(StudentId),
    'description' : IDL.Text,
    'roomNumber' : IDL.Text,
  });
  const ComplaintId = IDL.Nat;
  const NoteId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'emptyRoom' : IDL.Null,
    'complaintUpdate' : IDL.Null,
    'paymentOverdue' : IDL.Null,
    'rentDue' : IDL.Null,
  });
  const NotificationInput = IDL.Record({
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'message' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Nat),
  });
  const NotificationId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const PaymentInput = IDL.Record({
    'status' : PaymentStatus,
    'month' : IDL.Nat,
    'studentId' : StudentId,
    'note' : IDL.Opt(IDL.Text),
    'year' : IDL.Nat,
    'rentDue' : IDL.Nat,
    'paidAmount' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  const ReminderId = IDL.Nat;
  const RoomInput = IDL.Record({
    'seatCount' : IDL.Nat,
    'roomNumber' : IDL.Text,
  });
  const RoomId = IDL.Nat;
  const SeatType = IDL.Variant({ 'typeA' : IDL.Null, 'typeB' : IDL.Null });
  const StudentInput = IDL.Record({
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'idProofText' : IDL.Text,
    'phone' : IDL.Text,
    'roomId' : IDL.Opt(RoomId),
    'seatType' : IDL.Opt(SeatType),
  });
  const UdharCategory = IDL.Variant({
    'other' : IDL.Null,
    'milk' : IDL.Null,
    'grocery' : IDL.Null,
  });
  const UdharInput = IDL.Record({
    'studentId' : StudentId,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : UdharCategory,
    'amount' : IDL.Nat,
  });
  const UdharId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const StaffAttendance = IDL.Record({
    'status' : AttendanceStatus,
    'staffId' : StaffId,
    'date' : IDL.Text,
  });
  const BuildingStats = IDL.Record({
    'totalEmptyRooms' : IDL.Nat,
    'totalSeats' : IDL.Nat,
    'totalActiveStudents' : IDL.Nat,
  });
  const ComplaintStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'id' : ComplaintId,
    'status' : ComplaintStatus,
    'studentId' : IDL.Opt(StudentId),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'roomNumber' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const HostelSettings = IDL.Record({ 'lateFeePerMonth' : IDL.Nat });
  const Amount = IDL.Nat;
  const SeatSummary = IDL.Record({
    'month' : IDL.Nat,
    'pricePerSeatA' : Amount,
    'pricePerSeatB' : Amount,
    'year' : IDL.Nat,
    'revenueA' : Amount,
    'revenueB' : Amount,
    'totalBookedSeats' : IDL.Nat,
    'totalRevenue' : Amount,
    'totalCapacity' : IDL.Nat,
    'emptySeats' : IDL.Nat,
    'bookedSeatsA' : IDL.Nat,
    'bookedSeatsB' : IDL.Nat,
  });
  const MonthKey = IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat });
  const MonthlyExpenses = IDL.Record({
    'key' : MonthKey,
    'other' : Amount,
    'rent' : Amount,
    'electricity' : Amount,
    'staffSalary' : Amount,
  });
  const MonthlyProfit = IDL.Record({
    'month' : IDL.Nat,
    'revenue' : Amount,
    'year' : IDL.Nat,
    'totalExpenses' : Amount,
    'profit' : IDL.Int,
  });
  const MonthlyStaffExpense = IDL.Record({
    'month' : IDL.Nat,
    'presentDays' : IDL.Nat,
    'year' : IDL.Nat,
    'workingDays' : IDL.Nat,
    'totalSalary' : IDL.Nat,
  });
  const SubscriptionStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'expired' : IDL.Null,
  });
  const SubscriptionRecord = IDL.Record({
    'status' : SubscriptionStatus,
    'planId' : IDL.Opt(PlanId),
    'expiryDate' : IDL.Opt(IDL.Int),
    'userId' : IDL.Principal,
    'trialStartDate' : IDL.Int,
  });
  const SubscriptionStatusResult = IDL.Record({
    'status' : SubscriptionStatus,
    'daysRemaining' : IDL.Nat,
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Nat),
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'month' : IDL.Nat,
    'studentId' : StudentId,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'dueDate' : IDL.Int,
    'lateFee' : IDL.Nat,
    'paidDate' : IDL.Opt(IDL.Int),
    'rentDue' : IDL.Nat,
    'paidAmount' : IDL.Nat,
  });
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'title' : IDL.Text,
    'remindAt' : IDL.Int,
    'createdAt' : IDL.Int,
    'isDone' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'createdAt' : IDL.Int,
    'seatCount' : IDL.Nat,
    'roomNumber' : IDL.Text,
    'occupiedSeats' : IDL.Nat,
  });
  const RoomSummary = IDL.Record({
    'id' : RoomId,
    'status' : IDL.Variant({
      'full' : IDL.Null,
      'empty' : IDL.Null,
      'partial' : IDL.Null,
    }),
    'seatCount' : IDL.Nat,
    'roomNumber' : IDL.Text,
    'occupiedSeats' : IDL.Nat,
  });
  const SeatConfig = IDL.Record({
    'pricePerSeatA' : Amount,
    'pricePerSeatB' : Amount,
    'totalCapacity' : IDL.Nat,
  });
  const Staff = IDL.Record({
    'id' : StaffId,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'monthlySalary' : IDL.Nat,
  });
  const StaffSalaryEntry = IDL.Record({
    'earnedSalary' : IDL.Nat,
    'staffId' : StaffId,
    'presentDays' : IDL.Nat,
    'name' : IDL.Text,
    'monthlySalary' : IDL.Nat,
    'totalWorkingDays' : IDL.Nat,
  });
  const StaffSalaryReport = IDL.Record({
    'month' : IDL.Nat,
    'totalEarned' : IDL.Nat,
    'year' : IDL.Nat,
    'entries' : IDL.Vec(StaffSalaryEntry),
    'workingDays' : IDL.Nat,
  });
  const StudentStatus = IDL.Variant({
    'active' : IDL.Null,
    'vacated' : IDL.Null,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'status' : StudentStatus,
    'documentKey' : IDL.Opt(IDL.Text),
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'photoKey' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'idProofText' : IDL.Text,
    'phone' : IDL.Text,
    'roomId' : IDL.Opt(RoomId),
    'leaveDate' : IDL.Opt(IDL.Int),
    'seatType' : IDL.Opt(SeatType),
  });
  const UdharEntry = IDL.Record({
    'id' : UdharId,
    'studentId' : StudentId,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isPaid' : IDL.Bool,
    'category' : UdharCategory,
    'amount' : IDL.Nat,
  });
  const UdharSummary = IDL.Record({
    'studentId' : StudentId,
    'totalOutstanding' : IDL.Nat,
    'entries' : IDL.Vec(UdharEntry),
  });
  const StudentSummary = IDL.Record({
    'id' : StudentId,
    'status' : StudentStatus,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'roomNumber' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'roomId' : IDL.Opt(RoomId),
    'leaveDate' : IDL.Opt(IDL.Int),
  });
  const YearlyChartEntry = IDL.Record({
    'month' : IDL.Nat,
    'profit' : IDL.Int,
  });
  const ExpenseInput = IDL.Record({
    'other' : Amount,
    'rent' : Amount,
    'electricity' : Amount,
    'staffSalary' : Amount,
  });
  
  return IDL.Service({
    'activateSubscription' : IDL.Func([PlanId], [], []),
    'addStaff' : IDL.Func(
        [StaffInput],
        [IDL.Variant({ 'ok' : StaffId, 'err' : IDL.Text })],
        [],
      ),
    'cancelSubscription' : IDL.Func([], [], []),
    'clearAllNotifications' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createComplaint' : IDL.Func(
        [ComplaintInput],
        [IDL.Variant({ 'ok' : ComplaintId, 'err' : IDL.Text })],
        [],
      ),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
    'createNotification' : IDL.Func(
        [NotificationInput],
        [IDL.Variant({ 'ok' : NotificationId, 'err' : IDL.Text })],
        [],
      ),
    'createPayment' : IDL.Func(
        [PaymentInput],
        [IDL.Variant({ 'ok' : PaymentId, 'err' : IDL.Text })],
        [],
      ),
    'createReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [ReminderId],
        [],
      ),
    'createRoom' : IDL.Func(
        [RoomInput],
        [IDL.Variant({ 'ok' : RoomId, 'err' : IDL.Text })],
        [],
      ),
    'createStudent' : IDL.Func(
        [StudentInput],
        [IDL.Variant({ 'ok' : StudentId, 'err' : IDL.Text })],
        [],
      ),
    'createUdharEntry' : IDL.Func(
        [UdharInput],
        [IDL.Variant({ 'ok' : UdharId, 'err' : IDL.Text })],
        [],
      ),
    'deleteComplaint' : IDL.Func(
        [ComplaintId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'deletePayment' : IDL.Func(
        [PaymentId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
    'deleteRoom' : IDL.Func(
        [RoomId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteStudent' : IDL.Func(
        [StudentId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUdharEntry' : IDL.Func(
        [UdharId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAttendanceByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(StaffAttendance)],
        ['query'],
      ),
    'getBuildingStats' : IDL.Func([], [BuildingStats], ['query']),
    'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getHostelSettings' : IDL.Func([], [HostelSettings], ['query']),
    'getMonthSeatSummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(SeatSummary)],
        ['query'],
      ),
    'getMonthlyExpenses' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(MonthlyExpenses)],
        ['query'],
      ),
    'getMonthlyProfit' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyProfit],
        ['query'],
      ),
    'getMonthlyStaffExpense' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyStaffExpense],
        ['query'],
      ),
    'getMySubscription' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionRecord)],
        ['query'],
      ),
    'getMySubscriptionStatus' : IDL.Func([], [SubscriptionStatusResult], []),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getRoom' : IDL.Func([RoomId], [IDL.Opt(Room)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
    'getSeatConfig' : IDL.Func([], [IDL.Opt(SeatConfig)], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getStaffAttendance' : IDL.Func(
        [StaffId, IDL.Nat, IDL.Nat],
        [IDL.Vec(StaffAttendance)],
        ['query'],
      ),
    'getStaffSalaryReport' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [StaffSalaryReport],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentPayments' : IDL.Func([StudentId], [IDL.Vec(Payment)], ['query']),
    'getStudentUdhar' : IDL.Func([StudentId], [UdharSummary], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(StudentSummary)], ['query']),
    'getTotalExpenses' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getUdharEntries' : IDL.Func([], [IDL.Vec(UdharEntry)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getYearlyProfitChart' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(YearlyChartEntry)],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markAttendance' : IDL.Func(
        [StaffId, IDL.Text, AttendanceStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markNotificationRead' : IDL.Func(
        [NotificationId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markReminderDone' : IDL.Func([ReminderId], [IDL.Bool], []),
    'markUdharPaid' : IDL.Func(
        [UdharId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeStaff' : IDL.Func(
        [StaffId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setMonthlyBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'setMonthlyExpenses' : IDL.Func([IDL.Nat, IDL.Nat, ExpenseInput], [], []),
    'setSeatConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'startTrial' : IDL.Func([], [], []),
    'stripeWebhook' : IDL.Func([IDL.Principal, PlanId], [], []),
    'updateComplaintStatus' : IDL.Func(
        [ComplaintId, ComplaintStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateHostelSettings' : IDL.Func(
        [HostelSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updatePayment' : IDL.Func(
        [PaymentId, PaymentInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateReminder' : IDL.Func(
        [ReminderId, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Bool],
        [],
      ),
    'updateRoom' : IDL.Func(
        [RoomId, RoomInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateStaff' : IDL.Func(
        [StaffId, StaffInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateStudent' : IDL.Func(
        [StudentId, StudentInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateStudentDocument' : IDL.Func(
        [StudentId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateStudentPhoto' : IDL.Func(
        [StudentId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateUdharEntry' : IDL.Func(
        [UdharId, UdharInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'vacateStudent' : IDL.Func(
        [StudentId, IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };