/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Amount = bigint;
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface BuildingStats {
  'totalEmptyRooms' : bigint,
  'totalSeats' : bigint,
  'totalActiveStudents' : bigint,
}
export interface Complaint {
  'id' : ComplaintId,
  'status' : ComplaintStatus,
  'studentId' : [] | [StudentId],
  'createdAt' : bigint,
  'description' : string,
  'roomNumber' : string,
  'updatedAt' : bigint,
}
export type ComplaintId = bigint;
export interface ComplaintInput {
  'studentId' : [] | [StudentId],
  'description' : string,
  'roomNumber' : string,
}
export type ComplaintStatus = { 'resolved' : null } |
  { 'pending' : null } |
  { 'inProgress' : null };
export interface ExpenseInput {
  'other' : Amount,
  'rent' : Amount,
  'electricity' : Amount,
  'staffSalary' : Amount,
}
export interface HostelSettings { 'lateFeePerMonth' : bigint }
export interface MonthKey { 'month' : bigint, 'year' : bigint }
export interface MonthlyExpenses {
  'key' : MonthKey,
  'other' : Amount,
  'rent' : Amount,
  'electricity' : Amount,
  'staffSalary' : Amount,
}
export interface MonthlyProfit {
  'month' : bigint,
  'revenue' : Amount,
  'year' : bigint,
  'totalExpenses' : Amount,
  'profit' : bigint,
}
export interface MonthlyStaffExpense {
  'month' : bigint,
  'presentDays' : bigint,
  'year' : bigint,
  'workingDays' : bigint,
  'totalSalary' : bigint,
}
export interface Note {
  'id' : NoteId,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export type NoteId = bigint;
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'notifType' : NotificationType,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'relatedId' : [] | [bigint],
}
export type NotificationId = bigint;
export interface NotificationInput {
  'title' : string,
  'notifType' : NotificationType,
  'message' : string,
  'relatedId' : [] | [bigint],
}
export type NotificationType = { 'emptyRoom' : null } |
  { 'complaintUpdate' : null } |
  { 'paymentOverdue' : null } |
  { 'rentDue' : null };
export interface Payment {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'month' : bigint,
  'studentId' : StudentId,
  'note' : [] | [string],
  'createdAt' : bigint,
  'year' : bigint,
  'dueDate' : bigint,
  'lateFee' : bigint,
  'paidDate' : [] | [bigint],
  'rentDue' : bigint,
  'paidAmount' : bigint,
}
export type PaymentId = bigint;
export interface PaymentInput {
  'status' : PaymentStatus,
  'month' : bigint,
  'studentId' : StudentId,
  'note' : [] | [string],
  'year' : bigint,
  'rentDue' : bigint,
  'paidAmount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'partial' : null };
export type PlanId = { 'biannual' : null } |
  { 'annual' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export interface Reminder {
  'id' : ReminderId,
  'title' : string,
  'remindAt' : bigint,
  'createdAt' : bigint,
  'isDone' : boolean,
  'message' : string,
}
export type ReminderId = bigint;
export interface Room {
  'id' : RoomId,
  'createdAt' : bigint,
  'seatCount' : bigint,
  'roomNumber' : string,
  'occupiedSeats' : bigint,
}
export type RoomId = bigint;
export interface RoomInput { 'seatCount' : bigint, 'roomNumber' : string }
export interface RoomSummary {
  'id' : RoomId,
  'status' : { 'full' : null } |
    { 'empty' : null } |
    { 'partial' : null },
  'seatCount' : bigint,
  'roomNumber' : string,
  'occupiedSeats' : bigint,
}
export interface SeatConfig {
  'pricePerSeatA' : Amount,
  'pricePerSeatB' : Amount,
  'totalCapacity' : bigint,
}
export interface SeatSummary {
  'month' : bigint,
  'pricePerSeatA' : Amount,
  'pricePerSeatB' : Amount,
  'year' : bigint,
  'revenueA' : Amount,
  'revenueB' : Amount,
  'totalBookedSeats' : bigint,
  'totalRevenue' : Amount,
  'totalCapacity' : bigint,
  'emptySeats' : bigint,
  'bookedSeatsA' : bigint,
  'bookedSeatsB' : bigint,
}
export type SeatType = { 'typeA' : null } |
  { 'typeB' : null };
export interface Staff {
  'id' : StaffId,
  'joinDate' : bigint,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'monthlySalary' : bigint,
}
export interface StaffAttendance {
  'status' : AttendanceStatus,
  'staffId' : StaffId,
  'date' : string,
}
export type StaffId = bigint;
export interface StaffInput {
  'joinDate' : bigint,
  'name' : string,
  'role' : string,
  'monthlySalary' : bigint,
}
export interface StaffSalaryEntry {
  'earnedSalary' : bigint,
  'staffId' : StaffId,
  'presentDays' : bigint,
  'name' : string,
  'monthlySalary' : bigint,
  'totalWorkingDays' : bigint,
}
export interface StaffSalaryReport {
  'month' : bigint,
  'totalEarned' : bigint,
  'year' : bigint,
  'entries' : Array<StaffSalaryEntry>,
  'workingDays' : bigint,
}
export interface Student {
  'id' : StudentId,
  'status' : StudentStatus,
  'documentKey' : [] | [string],
  'joinDate' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'photoKey' : [] | [string],
  'address' : string,
  'idProofText' : string,
  'phone' : string,
  'roomId' : [] | [RoomId],
  'leaveDate' : [] | [bigint],
  'seatType' : [] | [SeatType],
}
export type StudentId = bigint;
export interface StudentInput {
  'joinDate' : bigint,
  'name' : string,
  'address' : string,
  'idProofText' : string,
  'phone' : string,
  'roomId' : [] | [RoomId],
  'seatType' : [] | [SeatType],
}
export type StudentStatus = { 'active' : null } |
  { 'vacated' : null };
export interface StudentSummary {
  'id' : StudentId,
  'status' : StudentStatus,
  'joinDate' : bigint,
  'name' : string,
  'roomNumber' : [] | [string],
  'phone' : string,
  'roomId' : [] | [RoomId],
  'leaveDate' : [] | [bigint],
}
export interface SubscriptionRecord {
  'status' : SubscriptionStatus,
  'planId' : [] | [PlanId],
  'expiryDate' : [] | [bigint],
  'userId' : Principal,
  'trialStartDate' : bigint,
}
export type SubscriptionStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'expired' : null };
export interface SubscriptionStatusResult {
  'status' : SubscriptionStatus,
  'daysRemaining' : bigint,
}
export type UdharCategory = { 'other' : null } |
  { 'milk' : null } |
  { 'grocery' : null };
export interface UdharEntry {
  'id' : UdharId,
  'studentId' : StudentId,
  'date' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'isPaid' : boolean,
  'category' : UdharCategory,
  'amount' : bigint,
}
export type UdharId = bigint;
export interface UdharInput {
  'studentId' : StudentId,
  'date' : bigint,
  'description' : string,
  'category' : UdharCategory,
  'amount' : bigint,
}
export interface UdharSummary {
  'studentId' : StudentId,
  'totalOutstanding' : bigint,
  'entries' : Array<UdharEntry>,
}
export interface YearlyChartEntry { 'month' : bigint, 'profit' : bigint }
export interface _SERVICE {
  'activateSubscription' : ActorMethod<[PlanId], undefined>,
  'addStaff' : ActorMethod<
    [StaffInput],
    { 'ok' : StaffId } |
      { 'err' : string }
  >,
  'cancelSubscription' : ActorMethod<[], undefined>,
  'clearAllNotifications' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createComplaint' : ActorMethod<
    [ComplaintInput],
    { 'ok' : ComplaintId } |
      { 'err' : string }
  >,
  'createNote' : ActorMethod<[string, string], NoteId>,
  'createNotification' : ActorMethod<
    [NotificationInput],
    { 'ok' : NotificationId } |
      { 'err' : string }
  >,
  'createPayment' : ActorMethod<
    [PaymentInput],
    { 'ok' : PaymentId } |
      { 'err' : string }
  >,
  'createReminder' : ActorMethod<[string, string, bigint], ReminderId>,
  'createRoom' : ActorMethod<
    [RoomInput],
    { 'ok' : RoomId } |
      { 'err' : string }
  >,
  'createStudent' : ActorMethod<
    [StudentInput],
    { 'ok' : StudentId } |
      { 'err' : string }
  >,
  'createUdharEntry' : ActorMethod<
    [UdharInput],
    { 'ok' : UdharId } |
      { 'err' : string }
  >,
  'deleteComplaint' : ActorMethod<
    [ComplaintId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteNote' : ActorMethod<[NoteId], boolean>,
  'deletePayment' : ActorMethod<
    [PaymentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteReminder' : ActorMethod<[ReminderId], boolean>,
  'deleteRoom' : ActorMethod<[RoomId], { 'ok' : null } | { 'err' : string }>,
  'deleteStudent' : ActorMethod<
    [StudentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteUdharEntry' : ActorMethod<
    [UdharId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAttendanceByMonth' : ActorMethod<
    [bigint, bigint],
    Array<StaffAttendance>
  >,
  'getBuildingStats' : ActorMethod<[], BuildingStats>,
  'getComplaints' : ActorMethod<[], Array<Complaint>>,
  'getHostelSettings' : ActorMethod<[], HostelSettings>,
  'getMonthSeatSummary' : ActorMethod<[bigint, bigint], [] | [SeatSummary]>,
  'getMonthlyExpenses' : ActorMethod<[bigint, bigint], [] | [MonthlyExpenses]>,
  'getMonthlyProfit' : ActorMethod<[bigint, bigint], MonthlyProfit>,
  'getMonthlyStaffExpense' : ActorMethod<[bigint, bigint], MonthlyStaffExpense>,
  'getMySubscription' : ActorMethod<[], [] | [SubscriptionRecord]>,
  'getMySubscriptionStatus' : ActorMethod<[], SubscriptionStatusResult>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPayments' : ActorMethod<[], Array<Payment>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getRoom' : ActorMethod<[RoomId], [] | [Room]>,
  'getRooms' : ActorMethod<[], Array<RoomSummary>>,
  'getSeatConfig' : ActorMethod<[], [] | [SeatConfig]>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getStaffAttendance' : ActorMethod<
    [StaffId, bigint, bigint],
    Array<StaffAttendance>
  >,
  'getStaffSalaryReport' : ActorMethod<[bigint, bigint], StaffSalaryReport>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentPayments' : ActorMethod<[StudentId], Array<Payment>>,
  'getStudentUdhar' : ActorMethod<[StudentId], UdharSummary>,
  'getStudents' : ActorMethod<[], Array<StudentSummary>>,
  'getTotalExpenses' : ActorMethod<[bigint, bigint], bigint>,
  'getUdharEntries' : ActorMethod<[], Array<UdharEntry>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getYearlyProfitChart' : ActorMethod<[bigint], Array<YearlyChartEntry>>,
  'markAllNotificationsRead' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markAttendance' : ActorMethod<
    [StaffId, string, AttendanceStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markNotificationRead' : ActorMethod<
    [NotificationId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markReminderDone' : ActorMethod<[ReminderId], boolean>,
  'markUdharPaid' : ActorMethod<
    [UdharId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeStaff' : ActorMethod<[StaffId], { 'ok' : null } | { 'err' : string }>,
  'setMonthlyBooking' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    undefined
  >,
  'setMonthlyExpenses' : ActorMethod<[bigint, bigint, ExpenseInput], undefined>,
  'setSeatConfig' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'startTrial' : ActorMethod<[], undefined>,
  'stripeWebhook' : ActorMethod<[Principal, PlanId], undefined>,
  'updateComplaintStatus' : ActorMethod<
    [ComplaintId, ComplaintStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateHostelSettings' : ActorMethod<
    [HostelSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateNote' : ActorMethod<[NoteId, string, string], boolean>,
  'updatePayment' : ActorMethod<
    [PaymentId, PaymentInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateReminder' : ActorMethod<[ReminderId, string, string, bigint], boolean>,
  'updateRoom' : ActorMethod<
    [RoomId, RoomInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStaff' : ActorMethod<
    [StaffId, StaffInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStudent' : ActorMethod<
    [StudentId, StudentInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStudentDocument' : ActorMethod<
    [StudentId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStudentPhoto' : ActorMethod<
    [StudentId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateUdharEntry' : ActorMethod<
    [UdharId, UdharInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'vacateStudent' : ActorMethod<
    [StudentId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];